package it.unipi.distribooked.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.bson.types.ObjectId;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;

/**
 * Model class for Reservation.
 *
 * Represents a reservation made by a user for a book in a specific library.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "reservations") // Maps this class to the "reservations" collection in MongoDB
public class Reservation {

    @Id
    private ObjectId id; // Unique ID for the reservation, auto-generated by MongoDB

    private ObjectId userId; // Reference to the user who made the reservation

    private ObjectId bookId; // Reference to the reserved book

    private ObjectId libraryId; // Reference to the library where the reservation was made

    private LocalDateTime reservedAt; // Timestamp when the reservation was created

    private LocalDateTime expiresAt; // Timestamp when the reservation will expire
}
